# Generated by Django 4.2.5 on 2023-09-27 14:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('spot_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('main_image', models.ImageField(upload_to='spot_image/')),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=400)),
                ('gallery', models.ManyToManyField(blank=True, null=True, to='city_spot.gallery')),
            ],
        ),
    ]
