# Generated by Django 4.2.5 on 2023-09-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_spot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='spot_type',
            field=models.CharField(choices=[('Shelter', 'shelter'), ('Shopping', 'shopping'), ('Waterfall', 'waterfall'), ('Trek', 'trek'), ('Temple', 'temple')], default='N/A', max_length=120),
        ),
    ]
