# Generated by Django 4.2.5 on 2023-09-27 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city_spot', '0005_trip_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='profile_id',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_instance',
            new_name='user',
        ),
    ]
