# Generated by Django 4.2.5 on 2023-09-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_spot', '0006_rename_user_id_profile_profile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='trips',
            field=models.ManyToManyField(blank=True, null=True, to='city_spot.trip'),
        ),
    ]
