# Generated by Django 4.2.5 on 2023-09-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_spot', '0008_trip_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='city',
        ),
        migrations.AlterField(
            model_name='trip',
            name='spots',
            field=models.ManyToManyField(blank=True, null=True, to='city_spot.spot'),
        ),
    ]
