# Generated by Django 4.2.5 on 2023-09-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_spot', '0009_remove_trip_city_alter_trip_spots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='trips',
            field=models.ManyToManyField(to='city_spot.trip'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='gallery',
            field=models.ManyToManyField(to='city_spot.gallery'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='spots',
            field=models.ManyToManyField(to='city_spot.spot'),
        ),
    ]
