# Generated by Django 4.2.5 on 2023-09-28 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_spot', '0010_alter_profile_trips_alter_spot_gallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='spot_type',
            field=models.CharField(choices=[('Shelter', 'shelter'), ('Shopping', 'shopping'), ('Waterfall', 'waterfall'), ('Lake', 'lake'), ('Trek', 'trek'), ('Temple', 'temple')], default='N/A', max_length=120),
        ),
    ]
